monolog:
    channels: ['app_info', 'app_search']

    handlers:
        appinfo:
            type: stream
            path: "%kernel.logs_dir%/appinfo.log"
            level: debug
            channels: ["app_info"]
            buffer_size: 500

        appsearch:
            type: stream
            path: "%kernel.logs_dir%/appsearch.log"
            level: debug
            channels: ["app_search"]
            buffer_size: 500